config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('about', views.about_page_view, name='about'),
    path('info', views.info_page_view, name='info')
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

def home_page_view(request):
	return render(request, "website/home.html")

def about_page_view(request):
	return render(request, "website/about.html")

def info_page_view(request):
	return render(request, "website/info.html")

website/templates/website/about.html
{% extends "website/base.html" %}

{% block main %}
    <h3>About</h3>
    <p>Ganda about the website wow grande website </p>
{% endblock %}

{% block aside %}
   {% load static %}
                <img style="width: 200px;height: 150px;" src="{% static "website/images/idk.jpg" %}" alt="IDK">
{% endblock %}

website/templates/website/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>GANDA WEBSITE</title>
        {% load static %}
            <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
     </head>
     <body>
        <header class="jumbotron text-center">
            <h1>Ganda Website - DJANGO</h1>
            <p>Djago Python Html</p>
            <nav>
                <a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
                <a href="{% url 'website:about' %}" class="btn btn-info">About</a>
                <a href="{% url 'website:info' %}" class="btn btn-info">Info</a>
            </nav>
        </header>
        <center>
            <article class="container">
                <main class="col-sm-6">
                    {% block main %}
                    {% endblock main %}
                </main>
                <aside class="col-sm-6">
                    {% block aside %}
                    {% endblock aside %}
                </aside>
            </article>
            <footer><p style="text-align: center">JOÃO LIMA a21906948</p></footer>
        </center>
    </body>
</html>

website/templates/website/home.html
{% extends "website/base.html" %}

{% block main %}
    <h3>Home</h3>
    <p>Welcome to my website ganda website</p>
{% endblock %}

{% block aside %}
   {% load static %}
                <img style="width: 200px;height: 150px;"  src="{% static "website/images/idk.jpg" %}" alt="IDK">
{% endblock %}

website/templates/website/info.html
{% extends "website/base.html" %}

{% block main %}
    <h3>Informação</h3>
    <p>O meu website foi feito ontem é grande websote</p>
{% endblock %}

{% block aside %}
   {% load static %}
                <img style="width: 200px;height: 150px;"  src="{% static "website/images/idk.jpg" %}" alt="IDK">
{% endblock %}